### ISSUE TITLE
Adding a top 10 scoreboard

### ISSUE THREAD

**Issue by marissam27** [marissam27/groupproject-team-4-namco-COMP55-resurrection#1]
I would add a new class that has an array pair holds a three letter string for the user name and an integer for the user score. 

Methods:
There will be a method to compare each score to compare old scores with the new score to determine where to insert the new score. After the new score has been inserted, the last score (11th score) will be deleted.
New score will move down the array if the new score is lower than the score of the current index. Once the new score finds a score that it is higher than, the new score will be inserted at the index before it. 
Example: 1-50    2- 45   3- 5    4-...       new score - 30  
                50 > 30           45> 30         5<30 
                1-50    2-45    3-30    4-5    5-...      

Another method will preset the top 10 scores to be '___ 0000' as default.

**Comment by onzfonz** [comment]
you can work on this scoreboard, but please make sure that the scoreboard does not reset every time the program is closed, so that way you have some persistence.
Knowing how to do this would end up helping you potentially with making something more general for the levels, but that will not be necessary to finish for the purposes of this course (but would be good for you to understand how that would work)

Let me know if you have question about it!
